#!/bin/bash

set -e 

NAME='top.py'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

# echo -e "${GREEN}Running python3 top.py${NC}"
# python3 $NAME
# sleep 1

echo -e "${RED}Argument Test:${NC}"
echo -e "${GREEN}Running python3 $NAME --version${NC}"
python3 $NAME --version