#!/bin/bash
set -e 

NAME='system_monitor.py'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Running python3 ${NAME} ${NC}"
python3 $NAME
echo -e "${RED}Finished running python3 ${NAME}${NC}"
# sleep 1

# echo -e "${GREEN}Running python3 $NAME --version${NC}"
# python3 $NAME --version
